# Voice Separator by Fernando Paladini
# GitHub: https://github.com/paladini
version: '3.8'

services:
  voice-separator:
    build: .
    container_name: voice-separator
    ports:
      - "8000:8000"
    volumes:
      - ./static/output:/app/static/output      # Output files (accessible on host)
      - model-cache:/root/.cache                # Model cache (persistent)
    environment:
      - PYTHONUNBUFFERED=1
      - TORCH_HOME=/root/.cache/torch
    restart: unless-stopped

# Named volumes for persistence
volumes:
  model-cache:
