# Voice Separator by Fernando Paladini
# GitHub: https://github.com/paladini
version: '3.8'

services:
  voice-separator:
    build: .
    container_name: voice-separator
    ports:
      - "8000:8000"
    volumes:
      - ./static/output:/app/static/output    # Processed files
      - model-cache:/home/app/.cache          # Model cache (persistent)
    environment:
      - PYTHONUNBUFFERED=1
      - TORCH_HOME=/home/app/.cache/torch
    restart: unless-stopped

# Named volume for model cache
volumes:
  model-cache:
